package com.adnroidlearningkts.databinding

import android.os.Bundle
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.databinding.DataBindingUtil
import com.adnroidlearningkts.R
import com.adnroidlearningkts.databinding.model.Person

class DataBindingActivity : AppCompatActivity() {

    /**
     * class generated by Android DataBinding library based on the name of layout file
     */
    private lateinit var binding: ActivityDataBindingBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        /**
         * init binding object
         *
         * replace setContentView(R.layout.activity_data_binding) call with
         *
         * use DataBindingUtil to set activity layout with data binding
         */
        binding = DataBindingUtil.setContentView(this, R.layout.activity_data_binding)

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }


        val person = Person("jack")

        binding.person = person

        binding.clickHandler = ClickHandler(this)

        /**
         * 2 way Data Binding
         */
    }

}